/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ComponentsEditor: typeof import('./src/components/panel/setting-panel/componentsEditor.vue')['default']
    DesignerRender: typeof import('./src/components/render/designerRender/index.vue')['default']
    EditorRender: typeof import('./src/components/render/editor-render/index.vue')['default']
    PagerEditor: typeof import('./src/components/panel/setting-panel/pagerEditor.vue')['default']
    PrintEditor: typeof import('./src/components/panel/setting-panel/printEditor.vue')['default']
    SizeControl: typeof import('./src/components/panel/sizeControl.vue')['default']
    TableEditor: typeof import('./src/components/panel/setting-panel/widget-editor/table-editor.vue')['default']
    TableWidget: typeof import('./src/components/panel/widgets/table-widget.vue')['default']
    TextEditor: typeof import('./src/components/panel/setting-panel/widget-editor/text-editor.vue')['default']
    TextWidget: typeof import('./src/components/panel/widgets/text-widget.vue')['default']
  }
}
